# Generated by Django 3.2.12 on 2023-03-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0006_alter_premium_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodpref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='~', max_length=200)),
                ('pref', models.CharField(default='~', max_length=50)),
            ],
        ),
    ]
