# Generated by Django 3.2.12 on 2023-03-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0007_foodpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='email',
            field=models.CharField(default='~', max_length=128),
        ),
    ]
